// Generated by CoffeeScript 1.6.3
(function() {
  var canvas, context, count, deg2rad, delay, drawCircle, drawHeart, drawLine, drawSide, radius, rx, ry, sleep, step;

  rx = 200;

  ry = 200;

  radius = 180;

  sleep = 0;

  count = 0;

  step = 5;

  canvas = void 0;

  context = void 0;

  deg2rad = function(x) {
    return x * Math.PI / 180;
  };

  drawCircle = function(x, y, r) {
    context.beginPath();
    context.arc(x, y, r, 0, Math.PI * 2, true);
    context.stroke();
  };

  window.drawLine = drawLine = function(x1, y1, x2, y2) {
    context.beginPath();
    context.moveTo(x1, y1);
    context.lineTo(x2, y2);
    context.stroke();
    if (count === 82) {
      count = 0;
      sleep = 0;
    }
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  drawSide = function(begin1, end1, step1, begin2, step2) {
    var d1, d2, x1, x2, y1, y2;
    while (begin1 !== end1 + step1) {
      d1 = deg2rad(begin1);
      d2 = deg2rad(begin2);
      x1 = rx + radius * Math.cos(d1);
      y1 = ry - radius * Math.sin(d1);
      x2 = rx + radius * Math.cos(d2);
      y2 = ry - radius * Math.sin(d2);
      delay(sleep * 100, (function(x1, y1, x2, y2) {
        return function() {
          return drawLine.call(this, x1, y1, x2, y2);
        };
      })(x1, y1, x2, y2));
      sleep += 1;
      begin1 += step1;
      begin2 += step2;
    }
  };

  drawHeart = function(containerSelector) {
    var $canvas, $container, height, width;
    $container = $(containerSelector);
    width = $container.width() - 20;
    height = width;
    radius = width / 2;
    rx = radius;
    ry = radius;
    $canvas = $('<canvas></canvas>').attr('width', width).attr('height', height).appendTo($container);
    canvas = $canvas.get(0);
    context = canvas.getContext('2d');
    context.clearRect(0, 0, canvas.width, canvas.height);
    context.strokeStyle = "black";
    drawCircle(rx, ry, radius);
    context.strokeStyle = "red";
    drawSide(-90, 0, step, 0, step);
    drawSide(-90, -180, -step, -180, -step);
    drawSide(0, 180, step, 90, step * 2);
  };

  window.drawHeart = drawHeart;

}).call(this);
